services:
  - type: web
    name: server-opencv
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: BACKEND_URL
        value: https://human-anomaly-detection-backend.onrender.com
      - key: FRAME_INTERVAL_MS
        value: "200"
